### ISSUE TITLE
Solution Documentation

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#199] opened 2020-12-09 15:55 UTC
## Description

What: 
 - Descriptive documentation on solution, components & architecture
 - Developer documentation focused on guided walkthroughs & implementation details
 
Why:
- consumer and developer experience

When:
- ongoing

Where:
 - GitHub Repo

**Comment by jofultz** [comment] 2021-01-11 17:02
Closing as duplicate of #261

**Closed by jofultz** 2021-01-11 17:02 UTC
Labels: Documentation, EngPrac
