### ISSUE TITLE
Fluentbit Container Update

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#259] opened 2020-12-16 15:22 UTC
## Description

What: 
 - 
 
Why:
- 

When:
- 

Where:
 - 

## Tasks
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

## Acceptance Criteria

- 

## Constraints
- N/A 

## References:
- References #16

**Comment by jofultz** [comment] 2021-01-05 20:08
Closing as duplicate of #284.

**Closed by jofultz** 2021-01-05 20:08 UTC
Labels: DevOps, PreProd
